apiVersion: v1
kind: Service
metadata:
  name: conversations
  labels:
    app: conversations
spec:
  type: NodePort
  ports:
    - port: 8080
      name: traffic
      targetPort: 8080
      protocol: TCP
    - port: 8081
      name: health
      targetPort: 8081
      protocol: TCP
  selector:
    app: pingpong-conversations-api
