// Code generated by protoc-gen-go. DO NOT EDIT.
// source: conversations.proto

package conversations

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/infobloxopen/protoc-gen-gorm/options"
	conversation "github.com/mhconradt/proto/conversation"
	message "github.com/mhconradt/proto/message"
	status "github.com/mhconradt/proto/status"
	user "github.com/mhconradt/proto/user"
	field_mask "google.golang.org/genproto/protobuf/field_mask"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Action int32

const (
	Action_LIST   Action = 0
	Action_REMOVE Action = 1
	Action_NEW    Action = 2
)

var Action_name = map[int32]string{
	0: "LIST",
	1: "REMOVE",
	2: "NEW",
}

var Action_value = map[string]int32{
	"LIST":   0,
	"REMOVE": 1,
	"NEW":    2,
}

func (x Action) String() string {
	return proto.EnumName(Action_name, int32(x))
}

func (Action) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_85f0777c2f340ac0, []int{0}
}

type CreateConversationRequest struct {
	Conversation         *conversation.Conversation `protobuf:"bytes,1,opt,name=conversation,proto3" json:"conversation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *CreateConversationRequest) Reset()         { *m = CreateConversationRequest{} }
func (m *CreateConversationRequest) String() string { return proto.CompactTextString(m) }
func (*CreateConversationRequest) ProtoMessage()    {}
func (*CreateConversationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_85f0777c2f340ac0, []int{0}
}

func (m *CreateConversationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateConversationRequest.Unmarshal(m, b)
}
func (m *CreateConversationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateConversationRequest.Marshal(b, m, deterministic)
}
func (m *CreateConversationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateConversationRequest.Merge(m, src)
}
func (m *CreateConversationRequest) XXX_Size() int {
	return xxx_messageInfo_CreateConversationRequest.Size(m)
}
func (m *CreateConversationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateConversationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateConversationRequest proto.InternalMessageInfo

func (m *CreateConversationRequest) GetConversation() *conversation.Conversation {
	if m != nil {
		return m.Conversation
	}
	return nil
}

type CreateConversationResponse struct {
	Conversation         *conversation.Conversation `protobuf:"bytes,1,opt,name=conversation,proto3" json:"conversation,omitempty"`
	Status               *status.Status             `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *CreateConversationResponse) Reset()         { *m = CreateConversationResponse{} }
func (m *CreateConversationResponse) String() string { return proto.CompactTextString(m) }
func (*CreateConversationResponse) ProtoMessage()    {}
func (*CreateConversationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_85f0777c2f340ac0, []int{1}
}

func (m *CreateConversationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateConversationResponse.Unmarshal(m, b)
}
func (m *CreateConversationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateConversationResponse.Marshal(b, m, deterministic)
}
func (m *CreateConversationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateConversationResponse.Merge(m, src)
}
func (m *CreateConversationResponse) XXX_Size() int {
	return xxx_messageInfo_CreateConversationResponse.Size(m)
}
func (m *CreateConversationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateConversationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateConversationResponse proto.InternalMessageInfo

func (m *CreateConversationResponse) GetConversation() *conversation.Conversation {
	if m != nil {
		return m.Conversation
	}
	return nil
}

func (m *CreateConversationResponse) GetStatus() *status.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type UpdateConversationRequest struct {
	Conversation         *conversation.Conversation `protobuf:"bytes,1,opt,name=conversation,proto3" json:"conversation,omitempty"`
	UpdateMask           *field_mask.FieldMask      `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *UpdateConversationRequest) Reset()         { *m = UpdateConversationRequest{} }
func (m *UpdateConversationRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateConversationRequest) ProtoMessage()    {}
func (*UpdateConversationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_85f0777c2f340ac0, []int{2}
}

func (m *UpdateConversationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateConversationRequest.Unmarshal(m, b)
}
func (m *UpdateConversationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateConversationRequest.Marshal(b, m, deterministic)
}
func (m *UpdateConversationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateConversationRequest.Merge(m, src)
}
func (m *UpdateConversationRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateConversationRequest.Size(m)
}
func (m *UpdateConversationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateConversationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateConversationRequest proto.InternalMessageInfo

func (m *UpdateConversationRequest) GetConversation() *conversation.Conversation {
	if m != nil {
		return m.Conversation
	}
	return nil
}

func (m *UpdateConversationRequest) GetUpdateMask() *field_mask.FieldMask {
	if m != nil {
		return m.UpdateMask
	}
	return nil
}

type UpdateConversationResponse struct {
	Conversation         *conversation.Conversation `protobuf:"bytes,1,opt,name=conversation,proto3" json:"conversation,omitempty"`
	Status               *status.Status             `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *UpdateConversationResponse) Reset()         { *m = UpdateConversationResponse{} }
func (m *UpdateConversationResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateConversationResponse) ProtoMessage()    {}
func (*UpdateConversationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_85f0777c2f340ac0, []int{3}
}

func (m *UpdateConversationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateConversationResponse.Unmarshal(m, b)
}
func (m *UpdateConversationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateConversationResponse.Marshal(b, m, deterministic)
}
func (m *UpdateConversationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateConversationResponse.Merge(m, src)
}
func (m *UpdateConversationResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateConversationResponse.Size(m)
}
func (m *UpdateConversationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateConversationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateConversationResponse proto.InternalMessageInfo

func (m *UpdateConversationResponse) GetConversation() *conversation.Conversation {
	if m != nil {
		return m.Conversation
	}
	return nil
}

func (m *UpdateConversationResponse) GetStatus() *status.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type ListConversationsRequest struct {
	SubscriberId         int32                 `protobuf:"varint,1,opt,name=subscriber_id,json=subscriberId,proto3" json:"subscriber_id,omitempty"`
	ListMask             *field_mask.FieldMask `protobuf:"bytes,2,opt,name=list_mask,json=listMask,proto3" json:"list_mask,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ListConversationsRequest) Reset()         { *m = ListConversationsRequest{} }
func (m *ListConversationsRequest) String() string { return proto.CompactTextString(m) }
func (*ListConversationsRequest) ProtoMessage()    {}
func (*ListConversationsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_85f0777c2f340ac0, []int{4}
}

func (m *ListConversationsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListConversationsRequest.Unmarshal(m, b)
}
func (m *ListConversationsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListConversationsRequest.Marshal(b, m, deterministic)
}
func (m *ListConversationsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListConversationsRequest.Merge(m, src)
}
func (m *ListConversationsRequest) XXX_Size() int {
	return xxx_messageInfo_ListConversationsRequest.Size(m)
}
func (m *ListConversationsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListConversationsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListConversationsRequest proto.InternalMessageInfo

func (m *ListConversationsRequest) GetSubscriberId() int32 {
	if m != nil {
		return m.SubscriberId
	}
	return 0
}

func (m *ListConversationsRequest) GetListMask() *field_mask.FieldMask {
	if m != nil {
		return m.ListMask
	}
	return nil
}

type ListConversationsResponse struct {
	Conversation         *conversation.Conversation `protobuf:"bytes,1,opt,name=conversation,proto3" json:"conversation,omitempty"`
	Action               Action                     `protobuf:"varint,2,opt,name=action,proto3,enum=conversations.Action" json:"action,omitempty"`
	Status               *status.Status             `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *ListConversationsResponse) Reset()         { *m = ListConversationsResponse{} }
func (m *ListConversationsResponse) String() string { return proto.CompactTextString(m) }
func (*ListConversationsResponse) ProtoMessage()    {}
func (*ListConversationsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_85f0777c2f340ac0, []int{5}
}

func (m *ListConversationsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListConversationsResponse.Unmarshal(m, b)
}
func (m *ListConversationsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListConversationsResponse.Marshal(b, m, deterministic)
}
func (m *ListConversationsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListConversationsResponse.Merge(m, src)
}
func (m *ListConversationsResponse) XXX_Size() int {
	return xxx_messageInfo_ListConversationsResponse.Size(m)
}
func (m *ListConversationsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListConversationsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListConversationsResponse proto.InternalMessageInfo

func (m *ListConversationsResponse) GetConversation() *conversation.Conversation {
	if m != nil {
		return m.Conversation
	}
	return nil
}

func (m *ListConversationsResponse) GetAction() Action {
	if m != nil {
		return m.Action
	}
	return Action_LIST
}

func (m *ListConversationsResponse) GetStatus() *status.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type DeleteConversationRequest struct {
	Conversation         *conversation.Conversation `protobuf:"bytes,1,opt,name=conversation,proto3" json:"conversation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *DeleteConversationRequest) Reset()         { *m = DeleteConversationRequest{} }
func (m *DeleteConversationRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteConversationRequest) ProtoMessage()    {}
func (*DeleteConversationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_85f0777c2f340ac0, []int{6}
}

func (m *DeleteConversationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteConversationRequest.Unmarshal(m, b)
}
func (m *DeleteConversationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteConversationRequest.Marshal(b, m, deterministic)
}
func (m *DeleteConversationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteConversationRequest.Merge(m, src)
}
func (m *DeleteConversationRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteConversationRequest.Size(m)
}
func (m *DeleteConversationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteConversationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteConversationRequest proto.InternalMessageInfo

func (m *DeleteConversationRequest) GetConversation() *conversation.Conversation {
	if m != nil {
		return m.Conversation
	}
	return nil
}

type DeleteConversationResponse struct {
	Status               *status.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *DeleteConversationResponse) Reset()         { *m = DeleteConversationResponse{} }
func (m *DeleteConversationResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteConversationResponse) ProtoMessage()    {}
func (*DeleteConversationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_85f0777c2f340ac0, []int{7}
}

func (m *DeleteConversationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteConversationResponse.Unmarshal(m, b)
}
func (m *DeleteConversationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteConversationResponse.Marshal(b, m, deterministic)
}
func (m *DeleteConversationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteConversationResponse.Merge(m, src)
}
func (m *DeleteConversationResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteConversationResponse.Size(m)
}
func (m *DeleteConversationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteConversationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteConversationResponse proto.InternalMessageInfo

func (m *DeleteConversationResponse) GetStatus() *status.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type SendMessageRequest struct {
	Message              *message.Message `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SendMessageRequest) Reset()         { *m = SendMessageRequest{} }
func (m *SendMessageRequest) String() string { return proto.CompactTextString(m) }
func (*SendMessageRequest) ProtoMessage()    {}
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_85f0777c2f340ac0, []int{8}
}

func (m *SendMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMessageRequest.Unmarshal(m, b)
}
func (m *SendMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMessageRequest.Marshal(b, m, deterministic)
}
func (m *SendMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMessageRequest.Merge(m, src)
}
func (m *SendMessageRequest) XXX_Size() int {
	return xxx_messageInfo_SendMessageRequest.Size(m)
}
func (m *SendMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendMessageRequest proto.InternalMessageInfo

func (m *SendMessageRequest) GetMessage() *message.Message {
	if m != nil {
		return m.Message
	}
	return nil
}

type SendMessageResponse struct {
	// We send back an id so the user can remove the message from the pending queue once they receive it
	Message              *message.Message `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Status               *status.Status   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SendMessageResponse) Reset()         { *m = SendMessageResponse{} }
func (m *SendMessageResponse) String() string { return proto.CompactTextString(m) }
func (*SendMessageResponse) ProtoMessage()    {}
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_85f0777c2f340ac0, []int{9}
}

func (m *SendMessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMessageResponse.Unmarshal(m, b)
}
func (m *SendMessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMessageResponse.Marshal(b, m, deterministic)
}
func (m *SendMessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMessageResponse.Merge(m, src)
}
func (m *SendMessageResponse) XXX_Size() int {
	return xxx_messageInfo_SendMessageResponse.Size(m)
}
func (m *SendMessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendMessageResponse proto.InternalMessageInfo

func (m *SendMessageResponse) GetMessage() *message.Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *SendMessageResponse) GetStatus() *status.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type ListMessagesRequest struct {
	// the id of the conversation for which to listen for messages
	ConversationId int32 `protobuf:"varint,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	// The subscriber's ID
	SubscriberId int32 `protobuf:"varint,2,opt,name=subscriber_id,json=subscriberId,proto3" json:"subscriber_id,omitempty"`
	// The last message the user received.
	// Interestingly enough this could be used in tandem with the pub-sub. (start message id, etc.)
	StartMessageId       int32    `protobuf:"varint,3,opt,name=start_message_id,json=startMessageId,proto3" json:"start_message_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListMessagesRequest) Reset()         { *m = ListMessagesRequest{} }
func (m *ListMessagesRequest) String() string { return proto.CompactTextString(m) }
func (*ListMessagesRequest) ProtoMessage()    {}
func (*ListMessagesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_85f0777c2f340ac0, []int{10}
}

func (m *ListMessagesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListMessagesRequest.Unmarshal(m, b)
}
func (m *ListMessagesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListMessagesRequest.Marshal(b, m, deterministic)
}
func (m *ListMessagesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListMessagesRequest.Merge(m, src)
}
func (m *ListMessagesRequest) XXX_Size() int {
	return xxx_messageInfo_ListMessagesRequest.Size(m)
}
func (m *ListMessagesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListMessagesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListMessagesRequest proto.InternalMessageInfo

func (m *ListMessagesRequest) GetConversationId() int32 {
	if m != nil {
		return m.ConversationId
	}
	return 0
}

func (m *ListMessagesRequest) GetSubscriberId() int32 {
	if m != nil {
		return m.SubscriberId
	}
	return 0
}

func (m *ListMessagesRequest) GetStartMessageId() int32 {
	if m != nil {
		return m.StartMessageId
	}
	return 0
}

type ListMessagesResponse struct {
	Message *message.Message `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	// Questionable
	Action               Action         `protobuf:"varint,2,opt,name=action,proto3,enum=conversations.Action" json:"action,omitempty"`
	Status               *status.Status `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ListMessagesResponse) Reset()         { *m = ListMessagesResponse{} }
func (m *ListMessagesResponse) String() string { return proto.CompactTextString(m) }
func (*ListMessagesResponse) ProtoMessage()    {}
func (*ListMessagesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_85f0777c2f340ac0, []int{11}
}

func (m *ListMessagesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListMessagesResponse.Unmarshal(m, b)
}
func (m *ListMessagesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListMessagesResponse.Marshal(b, m, deterministic)
}
func (m *ListMessagesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListMessagesResponse.Merge(m, src)
}
func (m *ListMessagesResponse) XXX_Size() int {
	return xxx_messageInfo_ListMessagesResponse.Size(m)
}
func (m *ListMessagesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListMessagesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListMessagesResponse proto.InternalMessageInfo

func (m *ListMessagesResponse) GetMessage() *message.Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *ListMessagesResponse) GetAction() Action {
	if m != nil {
		return m.Action
	}
	return Action_LIST
}

func (m *ListMessagesResponse) GetStatus() *status.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type AddMemberRequest struct {
	ConversationId       int32    `protobuf:"varint,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	UserId               int32    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddMemberRequest) Reset()         { *m = AddMemberRequest{} }
func (m *AddMemberRequest) String() string { return proto.CompactTextString(m) }
func (*AddMemberRequest) ProtoMessage()    {}
func (*AddMemberRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_85f0777c2f340ac0, []int{12}
}

func (m *AddMemberRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddMemberRequest.Unmarshal(m, b)
}
func (m *AddMemberRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddMemberRequest.Marshal(b, m, deterministic)
}
func (m *AddMemberRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddMemberRequest.Merge(m, src)
}
func (m *AddMemberRequest) XXX_Size() int {
	return xxx_messageInfo_AddMemberRequest.Size(m)
}
func (m *AddMemberRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddMemberRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddMemberRequest proto.InternalMessageInfo

func (m *AddMemberRequest) GetConversationId() int32 {
	if m != nil {
		return m.ConversationId
	}
	return 0
}

func (m *AddMemberRequest) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type AddMemberResponse struct {
	Status               *status.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *AddMemberResponse) Reset()         { *m = AddMemberResponse{} }
func (m *AddMemberResponse) String() string { return proto.CompactTextString(m) }
func (*AddMemberResponse) ProtoMessage()    {}
func (*AddMemberResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_85f0777c2f340ac0, []int{13}
}

func (m *AddMemberResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddMemberResponse.Unmarshal(m, b)
}
func (m *AddMemberResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddMemberResponse.Marshal(b, m, deterministic)
}
func (m *AddMemberResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddMemberResponse.Merge(m, src)
}
func (m *AddMemberResponse) XXX_Size() int {
	return xxx_messageInfo_AddMemberResponse.Size(m)
}
func (m *AddMemberResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddMemberResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddMemberResponse proto.InternalMessageInfo

func (m *AddMemberResponse) GetStatus() *status.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type ListMembersRequest struct {
	// The conversation for which to list users
	ConversationId       int32    `protobuf:"varint,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	SubscriberId         int32    `protobuf:"varint,2,opt,name=subscriber_id,json=subscriberId,proto3" json:"subscriber_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListMembersRequest) Reset()         { *m = ListMembersRequest{} }
func (m *ListMembersRequest) String() string { return proto.CompactTextString(m) }
func (*ListMembersRequest) ProtoMessage()    {}
func (*ListMembersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_85f0777c2f340ac0, []int{14}
}

func (m *ListMembersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListMembersRequest.Unmarshal(m, b)
}
func (m *ListMembersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListMembersRequest.Marshal(b, m, deterministic)
}
func (m *ListMembersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListMembersRequest.Merge(m, src)
}
func (m *ListMembersRequest) XXX_Size() int {
	return xxx_messageInfo_ListMembersRequest.Size(m)
}
func (m *ListMembersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListMembersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListMembersRequest proto.InternalMessageInfo

func (m *ListMembersRequest) GetConversationId() int32 {
	if m != nil {
		return m.ConversationId
	}
	return 0
}

func (m *ListMembersRequest) GetSubscriberId() int32 {
	if m != nil {
		return m.SubscriberId
	}
	return 0
}

type ListMembersResponse struct {
	User *user.User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	// The type of action involved. Is this a new user, are we just listing the user, did they get removed, what happened here?
	Action Action `protobuf:"varint,2,opt,name=action,proto3,enum=conversations.Action" json:"action,omitempty"`
	// Deeply questionable
	Status               *status.Status `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ListMembersResponse) Reset()         { *m = ListMembersResponse{} }
func (m *ListMembersResponse) String() string { return proto.CompactTextString(m) }
func (*ListMembersResponse) ProtoMessage()    {}
func (*ListMembersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_85f0777c2f340ac0, []int{15}
}

func (m *ListMembersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListMembersResponse.Unmarshal(m, b)
}
func (m *ListMembersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListMembersResponse.Marshal(b, m, deterministic)
}
func (m *ListMembersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListMembersResponse.Merge(m, src)
}
func (m *ListMembersResponse) XXX_Size() int {
	return xxx_messageInfo_ListMembersResponse.Size(m)
}
func (m *ListMembersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListMembersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListMembersResponse proto.InternalMessageInfo

func (m *ListMembersResponse) GetUser() *user.User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *ListMembersResponse) GetAction() Action {
	if m != nil {
		return m.Action
	}
	return Action_LIST
}

func (m *ListMembersResponse) GetStatus() *status.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type RemoveMemberRequest struct {
	ConversationId       int32    `protobuf:"varint,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	UserId               int32    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveMemberRequest) Reset()         { *m = RemoveMemberRequest{} }
func (m *RemoveMemberRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveMemberRequest) ProtoMessage()    {}
func (*RemoveMemberRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_85f0777c2f340ac0, []int{16}
}

func (m *RemoveMemberRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveMemberRequest.Unmarshal(m, b)
}
func (m *RemoveMemberRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveMemberRequest.Marshal(b, m, deterministic)
}
func (m *RemoveMemberRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveMemberRequest.Merge(m, src)
}
func (m *RemoveMemberRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveMemberRequest.Size(m)
}
func (m *RemoveMemberRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveMemberRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveMemberRequest proto.InternalMessageInfo

func (m *RemoveMemberRequest) GetConversationId() int32 {
	if m != nil {
		return m.ConversationId
	}
	return 0
}

func (m *RemoveMemberRequest) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type RemoveMemberResponse struct {
	Status               *status.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *RemoveMemberResponse) Reset()         { *m = RemoveMemberResponse{} }
func (m *RemoveMemberResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveMemberResponse) ProtoMessage()    {}
func (*RemoveMemberResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_85f0777c2f340ac0, []int{17}
}

func (m *RemoveMemberResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveMemberResponse.Unmarshal(m, b)
}
func (m *RemoveMemberResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveMemberResponse.Marshal(b, m, deterministic)
}
func (m *RemoveMemberResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveMemberResponse.Merge(m, src)
}
func (m *RemoveMemberResponse) XXX_Size() int {
	return xxx_messageInfo_RemoveMemberResponse.Size(m)
}
func (m *RemoveMemberResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveMemberResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveMemberResponse proto.InternalMessageInfo

func (m *RemoveMemberResponse) GetStatus() *status.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func init() {
	proto.RegisterEnum("conversations.Action", Action_name, Action_value)
	proto.RegisterType((*CreateConversationRequest)(nil), "conversations.CreateConversationRequest")
	proto.RegisterType((*CreateConversationResponse)(nil), "conversations.CreateConversationResponse")
	proto.RegisterType((*UpdateConversationRequest)(nil), "conversations.UpdateConversationRequest")
	proto.RegisterType((*UpdateConversationResponse)(nil), "conversations.UpdateConversationResponse")
	proto.RegisterType((*ListConversationsRequest)(nil), "conversations.ListConversationsRequest")
	proto.RegisterType((*ListConversationsResponse)(nil), "conversations.ListConversationsResponse")
	proto.RegisterType((*DeleteConversationRequest)(nil), "conversations.DeleteConversationRequest")
	proto.RegisterType((*DeleteConversationResponse)(nil), "conversations.DeleteConversationResponse")
	proto.RegisterType((*SendMessageRequest)(nil), "conversations.SendMessageRequest")
	proto.RegisterType((*SendMessageResponse)(nil), "conversations.SendMessageResponse")
	proto.RegisterType((*ListMessagesRequest)(nil), "conversations.ListMessagesRequest")
	proto.RegisterType((*ListMessagesResponse)(nil), "conversations.ListMessagesResponse")
	proto.RegisterType((*AddMemberRequest)(nil), "conversations.AddMemberRequest")
	proto.RegisterType((*AddMemberResponse)(nil), "conversations.AddMemberResponse")
	proto.RegisterType((*ListMembersRequest)(nil), "conversations.ListMembersRequest")
	proto.RegisterType((*ListMembersResponse)(nil), "conversations.ListMembersResponse")
	proto.RegisterType((*RemoveMemberRequest)(nil), "conversations.RemoveMemberRequest")
	proto.RegisterType((*RemoveMemberResponse)(nil), "conversations.RemoveMemberResponse")
}

func init() { proto.RegisterFile("conversations.proto", fileDescriptor_85f0777c2f340ac0) }

var fileDescriptor_85f0777c2f340ac0 = []byte{
	// 808 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x56, 0x4d, 0x4f, 0xdb, 0x4c,
	0x10, 0x7e, 0x0d, 0xbc, 0x01, 0x26, 0x81, 0x37, 0x6c, 0x78, 0x05, 0xf1, 0xa5, 0xd4, 0x1c, 0x92,
	0x22, 0xe1, 0x20, 0x38, 0x54, 0x6a, 0x4f, 0x08, 0x28, 0x8a, 0x44, 0xa8, 0x64, 0xbe, 0xd4, 0x13,
	0xb2, 0xe3, 0xc5, 0x58, 0x24, 0x5e, 0xd7, 0x6b, 0x23, 0xa4, 0xfe, 0x86, 0x5e, 0x7b, 0xac, 0xd4,
	0x73, 0xff, 0x46, 0x7f, 0x4e, 0x7f, 0x44, 0xe5, 0xf5, 0x3a, 0xfe, 0x58, 0xc7, 0x0d, 0x94, 0xa8,
	0x97, 0x38, 0x5e, 0xcf, 0x3c, 0xf3, 0xcc, 0xb3, 0xb3, 0x33, 0x0b, 0x8d, 0x3e, 0x71, 0xee, 0xb1,
	0x47, 0x75, 0xdf, 0x26, 0x0e, 0x55, 0x5d, 0x8f, 0xf8, 0x04, 0x2d, 0x65, 0x16, 0xe5, 0x0d, 0x8b,
	0x10, 0x6b, 0x80, 0x3b, 0xec, 0xa3, 0x11, 0xdc, 0x74, 0x6e, 0x6c, 0x3c, 0x30, 0xaf, 0x87, 0x3a,
	0xbd, 0x8b, 0x1c, 0xe4, 0x37, 0x96, 0xed, 0xdf, 0x06, 0x86, 0xda, 0x27, 0xc3, 0x8e, 0xed, 0xdc,
	0x10, 0x63, 0x40, 0x1e, 0x88, 0x8b, 0x9d, 0xc8, 0xa5, 0xbf, 0x6d, 0x61, 0x67, 0xdb, 0x22, 0xde,
	0xb0, 0x43, 0x5c, 0x06, 0xd9, 0x09, 0x5f, 0xb8, 0xaf, 0x9a, 0xf2, 0x1d, 0xde, 0xf6, 0x89, 0xe3,
	0xe9, 0xa6, 0x1f, 0x39, 0x76, 0xa8, 0xaf, 0xfb, 0x01, 0xe5, 0x0f, 0x6e, 0xbf, 0x55, 0x62, 0x1f,
	0x50, 0xec, 0xb1, 0x9f, 0x02, 0x5e, 0x79, 0xdb, 0x74, 0x8e, 0x99, 0x17, 0xee, 0xbb, 0x53, 0xe2,
	0x3b, 0xc4, 0x94, 0xea, 0x16, 0x8e, 0x9f, 0x91, 0x87, 0x62, 0x42, 0xf3, 0xc0, 0xc3, 0xba, 0x8f,
	0x0f, 0x52, 0x68, 0x1a, 0xfe, 0x18, 0x60, 0xea, 0xa3, 0x63, 0xa8, 0xa5, 0x83, 0xac, 0x4b, 0x1b,
	0x52, 0xbb, 0xba, 0xbb, 0xa9, 0xba, 0xb6, 0x63, 0xb9, 0xc4, 0xb1, 0xd4, 0x0c, 0x85, 0x0c, 0x42,
	0xc6, 0x51, 0xf9, 0x22, 0x81, 0x5c, 0x14, 0x86, 0xba, 0xc4, 0xa1, 0xf8, 0xd9, 0xe2, 0xa0, 0x0e,
	0x54, 0x22, 0xdd, 0xd7, 0x67, 0x18, 0xc4, 0x5a, 0x02, 0xc1, 0xf7, 0xe3, 0x8c, 0x3d, 0x34, 0x6e,
	0xa6, 0x7c, 0x93, 0xa0, 0x79, 0xe1, 0x9a, 0x53, 0xce, 0x1f, 0xbd, 0x85, 0x6a, 0xc0, 0xa2, 0xb0,
	0x02, 0xe4, 0xe4, 0x64, 0x35, 0xaa, 0x51, 0x35, 0xae, 0x51, 0xf5, 0x5d, 0x58, 0xa3, 0x3d, 0x9d,
	0xde, 0x69, 0x10, 0x99, 0x87, 0xff, 0x99, 0x78, 0x45, 0x1c, 0xff, 0xba, 0x78, 0x0f, 0xb0, 0x7e,
	0x62, 0x53, 0x3f, 0x0d, 0x49, 0x63, 0xe9, 0x36, 0x61, 0x89, 0x06, 0x06, 0xed, 0x7b, 0xb6, 0x81,
	0xbd, 0x6b, 0xdb, 0x64, 0xb4, 0xfe, 0xd5, 0x6a, 0xc9, 0x62, 0xd7, 0x44, 0xaf, 0x61, 0x71, 0x60,
	0x53, 0x7f, 0x52, 0x51, 0x16, 0x42, 0x63, 0x26, 0xc9, 0x0f, 0x09, 0x9a, 0x05, 0xa1, 0x9f, 0x5b,
	0x91, 0x6d, 0xa8, 0xe8, 0x7d, 0x06, 0x11, 0x92, 0x5b, 0xde, 0xfd, 0x5f, 0xcd, 0x76, 0x9e, 0x7d,
	0xf6, 0x51, 0xe3, 0x46, 0x29, 0x01, 0x67, 0x27, 0x13, 0xd0, 0x84, 0xe6, 0x21, 0x1e, 0xe0, 0x29,
	0x1f, 0xbe, 0x1e, 0xc8, 0x45, 0x51, 0xb8, 0x58, 0x09, 0x69, 0x69, 0x32, 0xd2, 0x5d, 0x40, 0x67,
	0xd8, 0x31, 0x7b, 0x51, 0x1b, 0x89, 0xd9, 0xee, 0xc1, 0x3c, 0x6f, 0x2c, 0x1c, 0xa7, 0x99, 0xe0,
	0xc4, 0x1d, 0x27, 0x76, 0x89, 0x2d, 0x95, 0x4f, 0xd0, 0xc8, 0x40, 0x71, 0x4a, 0x4f, 0xc1, 0x7a,
	0x7c, 0xf5, 0x7e, 0x96, 0xa0, 0x11, 0xd6, 0x10, 0x47, 0x1a, 0x55, 0x6e, 0x0b, 0xfe, 0x4b, 0xcb,
	0x97, 0xd4, 0xee, 0x72, 0x7a, 0xb9, 0x6b, 0x8a, 0x25, 0x3e, 0x53, 0x50, 0xe2, 0x6d, 0xa8, 0x53,
	0x5f, 0xf7, 0xfc, 0x6b, 0xce, 0x33, 0xb4, 0x9b, 0x8d, 0xe0, 0xd8, 0x3a, 0x8f, 0xde, 0x35, 0x95,
	0xef, 0x12, 0xac, 0x66, 0xf9, 0xfc, 0x89, 0x1c, 0xd3, 0x2e, 0xdd, 0x73, 0xa8, 0xef, 0x9b, 0x66,
	0x0f, 0x0f, 0x0d, 0xec, 0x3d, 0x5a, 0xb9, 0x35, 0x98, 0x0f, 0x07, 0x5e, 0xa2, 0x59, 0x25, 0x7c,
	0xed, 0x9a, 0xca, 0x21, 0xac, 0xa4, 0x50, 0x9f, 0x5a, 0xa1, 0x06, 0xa0, 0x48, 0xc8, 0x10, 0x66,
	0x3a, 0xfb, 0xaa, 0x7c, 0x1d, 0x55, 0x0f, 0x0f, 0xc2, 0xc9, 0xb6, 0x60, 0x2e, 0xcc, 0x85, 0x53,
	0x6d, 0x24, 0x54, 0xd9, 0x84, 0xbf, 0xa0, 0xd8, 0xd3, 0x98, 0xc1, 0xd4, 0x37, 0xe8, 0x0a, 0x1a,
	0x1a, 0x1e, 0x92, 0x7b, 0xfc, 0xdc, 0x7b, 0x74, 0x0c, 0xab, 0x59, 0xe0, 0x27, 0x6e, 0xd3, 0x56,
	0x0b, 0x2a, 0x51, 0x92, 0x68, 0x01, 0xe6, 0x4e, 0xba, 0x67, 0xe7, 0xf5, 0x7f, 0x10, 0x40, 0x45,
	0x3b, 0xea, 0xbd, 0xbf, 0x3c, 0xaa, 0x4b, 0x68, 0x1e, 0x66, 0x4f, 0x8f, 0xae, 0xea, 0x33, 0xbb,
	0x3f, 0x2b, 0xb0, 0x94, 0xe9, 0xf4, 0xc8, 0x06, 0x24, 0x5e, 0x27, 0x50, 0x3b, 0x27, 0xe1, 0xd8,
	0x8b, 0x8d, 0xfc, 0x6a, 0x02, 0x4b, 0x9e, 0x96, 0x0d, 0x48, 0x1c, 0xbe, 0x42, 0xa8, 0xb1, 0x77,
	0x08, 0x21, 0x54, 0xc9, 0x24, 0xbf, 0x85, 0x15, 0x61, 0xa8, 0xa1, 0x56, 0xce, 0x7f, 0xdc, 0xc4,
	0x95, 0xdb, 0xbf, 0x37, 0x8c, 0xe2, 0xec, 0x48, 0x61, 0x52, 0xe2, 0x48, 0x10, 0x92, 0x1a, 0x3b,
	0x9b, 0x84, 0xa4, 0x4a, 0xe6, 0xcb, 0x39, 0x54, 0x53, 0x3d, 0x1e, 0xbd, 0xcc, 0x79, 0x8a, 0xa3,
	0x44, 0x56, 0xca, 0x4c, 0x38, 0xea, 0x07, 0xa8, 0xa5, 0x7b, 0x25, 0x52, 0x0a, 0x92, 0xcf, 0x35,
	0x76, 0x79, 0xb3, 0xd4, 0x66, 0xa4, 0xcd, 0x29, 0x2c, 0x8e, 0x7a, 0x10, 0x7a, 0x91, 0x3f, 0x95,
	0xb9, 0x9e, 0x27, 0x6f, 0x8c, 0x37, 0xe0, 0x54, 0x2f, 0xa1, 0x9a, 0x6a, 0x14, 0x82, 0x00, 0x62,
	0xa7, 0x92, 0x95, 0x32, 0x93, 0x11, 0xcf, 0x2b, 0xa8, 0xa5, 0xcf, 0xa1, 0x20, 0x41, 0xc1, 0xe9,
	0x17, 0x24, 0x28, 0x3a, 0xc8, 0x46, 0x85, 0x5d, 0xbd, 0xf6, 0x7e, 0x05, 0x00, 0x00, 0xff, 0xff,
	0xcb, 0x07, 0xa6, 0x74, 0x67, 0x0d, 0x00, 0x00,
}
